apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: customer-cron-job
spec:
  schedule: "30 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: customer-cron-job
            image: "registry.tech1a.co:81/repository/tech1a-docker-registry/crawlers:latest"
            command:
            - "python3"
            - "/usr/src/app/customer.py"
            env:
            - name: MONGO_CONNECTION_STRING
              value: "mongodb://root:root@mongo-marketer-headless.dev-marketer-db.svc.cluster.local:27017/"
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: trades-cron-job
spec:
  schedule: "20 6,9,13,16 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: trades-cron-job
            image: "registry.tech1a.co:81/repository/tech1a-docker-registry/crawlers:latest"
            command:
            - "python3"
            - "/usr/src/app/trades.py"
            env:
            - name: MONGO_CONNECTION_STRING
              value: "mongodb://root:root@mongo-marketer-headless.dev-marketer-db.svc.cluster.local:27017/"
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: firms-cron-job
spec:
  schedule: "45 */4 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: firms-cron-job
            image: "registry.tech1a.co:81/repository/tech1a-docker-registry/crawlers:latest"
            command:
            - "python3"
            - "/usr/src/app/firm.py"
            env:
            - name: MONGO_CONNECTION_STRING
              value: "mongodb://root:root@mongo-marketer-headless.dev-marketer-db.svc.cluster.local:27017/"
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: assets0-cron-job
spec:
  schedule: "0 9 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: assets0-cron-job
            image: "registry.tech1a.co:81/repository/tech1a-docker-registry/crawlers:latest"
            command:
            - "python3"
            - "/usr/src/app/assets/assets0.py"
            env:
            - name: MONGO_CONNECTION_STRING
              value: "mongodb://root:root@mongo-marketer-headless.dev-marketer-db.svc.cluster.local:27017/"
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: assets1-cron-job
spec:
  schedule: "1 9 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: assets1-cron-job
            image: "registry.tech1a.co:81/repository/tech1a-docker-registry/crawlers:latest"
            command:
            - "python3"
            - "/usr/src/app/assets/assets1.py"
            env:
            - name: MONGO_CONNECTION_STRING
              value: "mongodb://root:root@mongo-marketer-headless.dev-marketer-db.svc.cluster.local:27017/"
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: assets2-cron-job
spec:
  schedule: "2 9 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: assets2-cron-job
            image: "registry.tech1a.co:81/repository/tech1a-docker-registry/crawlers:latest"
            command:
            - "python3"
            - "/usr/src/app/assets/assets2.py"
            env:
            - name: MONGO_CONNECTION_STRING
              value: "mongodb://root:root@mongo-marketer-headless.dev-marketer-db.svc.cluster.local:27017/"
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: assets3-cron-job
spec:
  schedule: "3 9 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: assets3-cron-job
            image: "registry.tech1a.co:81/repository/tech1a-docker-registry/crawlers:latest"
            command:
            - "python3"
            - "/usr/src/app/assets/assets3.py"
            env:
            - name: MONGO_CONNECTION_STRING
              value: "mongodb://root:root@mongo-marketer-headless.dev-marketer-db.svc.cluster.local:27017/"
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: assets4-cron-job
spec:
  schedule: "4 9 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: assets4-cron-job
            image: "registry.tech1a.co:81/repository/tech1a-docker-registry/crawlers:latest"
            command:
            - "python3"
            - "/usr/src/app/assets/assets4.py"
            env:
            - name: MONGO_CONNECTION_STRING
              value: "mongodb://root:root@mongo-marketer-headless.dev-marketer-db.svc.cluster.local:27017/"
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: assets5-cron-job
spec:
  schedule: "5 9 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: assets5-cron-job
            image: "registry.tech1a.co:81/repository/tech1a-docker-registry/crawlers:latest"
            command:
            - "python3"
            - "/usr/src/app/assets/assets5.py"
            env:
            - name: MONGO_CONNECTION_STRING
              value: "mongodb://root:root@mongo-marketer-headless.dev-marketer-db.svc.cluster.local:27017/"
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: assets6-cron-job
spec:
  schedule: "6 9 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: assets6-cron-job
            image: "registry.tech1a.co:81/repository/tech1a-docker-registry/crawlers:latest"
            command:
            - "python3"
            - "/usr/src/app/assets/assets6.py"
            env:
            - name: MONGO_CONNECTION_STRING
              value: "mongodb://root:root@mongo-marketer-headless.dev-marketer-db.svc.cluster.local:27017/"
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: assets7-cron-job
spec:
  schedule: "7 9 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: assets7-cron-job
            image: "registry.tech1a.co:81/repository/tech1a-docker-registry/crawlers:latest"
            command:
            - "python3"
            - "/usr/src/app/assets/assets7.py"
            env:
            - name: MONGO_CONNECTION_STRING
              value: "mongodb://root:root@mongo-marketer-headless.dev-marketer-db.svc.cluster.local:27017/"
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: assets8-cron-job
spec:
  schedule: "8 9 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: assets8-cron-job
            image: "registry.tech1a.co:81/repository/tech1a-docker-registry/crawlers:latest"
            command:
            - "python3"
            - "/usr/src/app/assets/assets8.py"
            env:
            - name: MONGO_CONNECTION_STRING
              value: "mongodb://root:root@mongo-marketer-headless.dev-marketer-db.svc.cluster.local:27017/"
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: assets9-cron-job
spec:
  schedule: "9 9 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: assets9-cron-job
            image: "registry.tech1a.co:81/repository/tech1a-docker-registry/crawlers:latest"
            command:
            - "python3"
            - "/usr/src/app/assets/assets9.py"
            env:
            - name: MONGO_CONNECTION_STRING
              value: "mongodb://root:root@mongo-marketer-headless.dev-marketer-db.svc.cluster.local:27017/"
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: assetsa-cron-job
spec:
  schedule: "10 9 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: assetsa-cron-job
            image: "registry.tech1a.co:81/repository/tech1a-docker-registry/crawlers:latest"
            command:
            - "python3"
            - "/usr/src/app/assets/assetsa.py"
            env:
            - name: MONGO_CONNECTION_STRING
              value: "mongodb://root:root@mongo-marketer-headless.dev-marketer-db.svc.cluster.local:27017/"
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: assetsb-cron-job
spec:
  schedule: "11 9 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: assetsb-cron-job
            image: "registry.tech1a.co:81/repository/tech1a-docker-registry/crawlers:latest"
            command:
            - "python3"
            - "/usr/src/app/assets/assetsb.py"
            env:
            - name: MONGO_CONNECTION_STRING
              value: "mongodb://root:root@mongo-marketer-headless.dev-marketer-db.svc.cluster.local:27017/"
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: assetsc-cron-job
spec:
  schedule: "12 9 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: assetsc-cron-job
            image: "registry.tech1a.co:81/repository/tech1a-docker-registry/crawlers:latest"
            command:
            - "python3"
            - "/usr/src/app/assets/assetsc.py"
            env:
            - name: MONGO_CONNECTION_STRING
              value: "mongodb://root:root@mongo-marketer-headless.dev-marketer-db.svc.cluster.local:27017/"
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: assetsd-cron-job
spec:
  schedule: "13 9 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: assetsd-cron-job
            image: "registry.tech1a.co:81/repository/tech1a-docker-registry/crawlers:latest"
            command:
            - "python3"
            - "/usr/src/app/assets/assetsd.py"
            env:
            - name: MONGO_CONNECTION_STRING
              value: "mongodb://root:root@mongo-marketer-headless.dev-marketer-db.svc.cluster.local:27017/"
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: assetse-cron-job
spec:
  schedule: "14 9 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: assetse-cron-job
            image: "registry.tech1a.co:81/repository/tech1a-docker-registry/crawlers:latest"
            command:
            - "python3"
            - "/usr/src/app/assets/assetse.py"
            env:
            - name: MONGO_CONNECTION_STRING
              value: "mongodb://root:root@mongo-marketer-headless.dev-marketer-db.svc.cluster.local:27017/"
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: assetsf-cron-job
spec:
  schedule: "15 9 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: assetsf-cron-job
            image: "registry.tech1a.co:81/repository/tech1a-docker-registry/crawlers:latest"
            command:
            - "python3"
            - "/usr/src/app/assets/assetsf.py"
            env:
            - name: MONGO_CONNECTION_STRING
              value: "mongodb://root:root@mongo-marketer-headless.dev-marketer-db.svc.cluster.local:27017/"
          restartPolicy: OnFailure

