apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: customer-cron-job
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: customer-cron-job
            image: "registry.tech1a.co:81/repository/tech1a-docker-registry/crawlers:latest"
            command:
            - "python3"
            - "-c"
            - "customer.py"
            env:
            - name: DATABASE_URL
              value: "mongodb://root:root@mongo-marketer.stg-marketer-db.svc.cluster.local:27017/"
          restartPolicy: OnFailure
