apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: customer-cron-job
spec:
  schedule: "30 23 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: customer-cron-job
            image: "registry.tech1a.co:81/repository/tech1a-docker-registry/crawlers:latest"
            command:
            - "python3"
            - "/usr/src/app/customer.py"
            env:
            - name: DATABASE_URL
              value: "mongodb://root:3tliSqt3tDD5Bg@mongo-marketer-0-external.stg-marketer-db.svc.cluster.local:27017/"
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: trades-cron-job
spec:
  schedule: "0 23 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: trades-cron-job
            image: "registry.tech1a.co:81/repository/tech1a-docker-registry/crawlers:latest"
            command:
            - "python3"
            - "/usr/src/app/trades.py"
            env:
            - name: DATABASE_URL
              value: "mongodb://root:root@mongo-marketer-0-external.stg-marketer-db.svc.cluster.local:27017/"
          restartPolicy: OnFailure
