apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: customer-cron-job
spec:
  schedule: "0 5,10,12,16,20 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: customer-cron-job
            image: "registry.tech1a.co:81/repository/tech1a-docker-registry/crawlers:latest"
            command:
            - "python3"
            - "/usr/src/app/customer.py"
            env:
            - name: MONGO_CONNECTION_STRING
              value: "mongodb://root:1219S4OiIhSXPJmOGfmdlFlsQ121@mongo-marketer-headless.pro-marketer-db.svc.cluster.local:27017/"
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: trades-cron-job
spec:
  schedule: "0 7,12,17 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: trades-cron-job
            image: "registry.tech1a.co:81/repository/tech1a-docker-registry/crawlers:latest"
            command:
            - "python3"
            - "/usr/src/app/trades.py"
            env:
            - name: MONGO_CONNECTION_STRING
              value: "mongodb://root:1219S4OiIhSXPJmOGfmdlFlsQ121@mongo-marketer-headless.pro-marketer-db.svc.cluster.local:27017/"
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: firms-cron-job
spec:
  schedule: "45 */4 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: firms-cron-job
            image: "registry.tech1a.co:81/repository/tech1a-docker-registry/crawlers:latest"
            command:
            - "python3"
            - "/usr/src/app/firm.py"
            env:
            - name: MONGO_CONNECTION_STRING
              value: "mongodb://root:1219S4OiIhSXPJmOGfmdlFlsQ121@mongo-marketer-headless.pro-marketer-db.svc.cluster.local:27017/"
          restartPolicy: OnFailure
